name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'packages/docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: |
          cd packages/docs
          pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:

          github_token: ${{ secrets.SNIPID_DOCS_DEPLOY_TOKEN }}
          publish_dir: ./packages/docs/dist
          force_orphan: true
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 'docs: 📝 Update docs'
